### PR TITLE
[WIP] Buzz 1.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by glennjacobs** [comment]
@GrahamCampbell can we delete this branch?

**Comment by GrahamCampbell** [comment]
Hmmm, Buzz 1.x support still needs addressing, but I never got around to it.

**Comment by GrahamCampbell** [comment]
But, yes, we can delete this branch since I never actually made any non-trivial changes.

**Comment by glennjacobs** [comment]
I'll make an issue for it.

**Pull request closed without merging**
