### PR TITLE
Update DomainRecord.php

### PR DESCRIPTION
**Pull request by i0**
The name of MX Record is assignable in DigitalOcean.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests are failing.

**Comment by GrahamCampbell** [comment]
@Teevio Are you able to finished this off please, and then I will tag a release. :)

**Comment by Teevio** [comment]
@GrahamCampbell indeed!

**Comment by Teevio** [comment]
I'm not sure if there's a better way to fix a PR that I don't own, but I fixed it over here https://github.com/toin0u/DigitalOceanV2/pull/167

**Pull request closed without merging**
