### PR TITLE
[4.0] DomainRecord create method missing optional name attribute for NS records

### PR DESCRIPTION
**Pull request by LewisSmallwood**
Here is a proposed solution for:
#265 DomainRecord create method missing optional name attribute for NS records

It also adds a check to see if the name attribute is not set, in which case, it will default back to "@" to maintain backwards compatibility with older versions of the Client.

### CODE REVIEW

**Comment by LewisSmallwood** [comment]
Contrary to the documentation from DO, the name attribute is required. Without it this error is thrown:

image

I have updated the PR accordingly.

**Comment by GrahamCampbell** [comment]
Can you contact them about this issue, please?

**Comment by GrahamCampbell** [comment]
Thanks for working on this. :)

**Comment by LewisSmallwood** [comment]
> Can you contact them about this issue, please?

@GrahamCampbell Yes, of course. I raised it with their partner team so it should be updated soon. 

Thanks for merging it in.  How often are the releases scheduled?

**Pull request merged**
