### PR TITLE
Include TTL in DomainRecord update request

### PR DESCRIPTION
**Pull request by mbardelmeijer**
Was missing from #174

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
@yassirh could you perhaps merge this? 😄

**Comment by GrahamCampbell** [comment]
Are there existing tests for this method? If so, please update them.

**Comment by GrahamCampbell** [comment]
If not, let me know, and I'll merge.

**Comment by GrahamCampbell** [comment]
Oh, I see there are tests, but not covering this method? Please could you add one?

**Comment by mbardelmeijer** [comment]
Yeah noticed that as well, should have updated it in the first place. Updated it now. Not used to working with phpspec, so hope everything is okay :)

**Comment by mbardelmeijer** [comment]
@GrahamCampbell could you have another look with the added test coverage?

**Pull request merged**
