### PR TITLE
Partial Firewall API support

### PR DESCRIPTION
**Pull request by bradt**
I'm currently using this in production.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks. Please target the 3.1 branch, because we follow semver.

**Comment by GrahamCampbell** [comment]
Thanks for working on this. Partial is better than none. :)

**Comment by sdwru** [comment]
Is there a reason this has not been added to Client.php or a separate class like ResultPager?

**Comment by GrahamCampbell** [comment]
That looks like a mistake. I'd accept a PR to correct this.

**Comment by sdwru** [comment]
Which branch?

**Comment by GrahamCampbell** [comment]
It's a bug fix, so 4.1 please.

**Comment by GrahamCampbell** [comment]
The 2.x and 3.x lines are now on security-fix only support.

**Pull request merged**
