### PR TITLE
toin0u/DigitalOceanV2#206 Remove support for PHP 7.1 and PHP HHVM

### PR DESCRIPTION
**Pull request by tspencer244**
Buzz library changes in 7.1 cause this library to break so I think you should drop support for it and release a version 3 of the library that supports PHP 7.1+

### CODE REVIEW

**Comment by yassirh** [comment]
I think you are right. Thanks!

**Comment by GrahamCampbell** [comment]
Dropping PHP 7.1 support is the wrong way to go, since this library does not actuallt require buzz, it's optional.

**Comment by yassirh** [comment]
@GrahamCampbell I was actually planning on making a second branch without buzz support. Do you have a better suggestion?

**Comment by GrahamCampbell** [comment]
The current situation is not broken. All that is wrong is the newest buzz releases don't work with the newest php versions. That doesn't prevent the rest of the library working, so current master is not broken.

**Pull request merged**
