### PR TITLE
Adding support for volumes and tags

### PR DESCRIPTION
**Pull request by Teevio**
This adds in API functionality for adding volumes and tags when creating a new Droplet.

### CODE REVIEW

**Comment by SpiLLeR** [comment]
@toin0u plz, accept this PR and tag it.

**Comment by GrahamCampbell** [comment]
Please add tests, and then I will merge this. :)

**Comment by Teevio** [comment]
Yup, sorry I keep forgetting about all the other chunks that need to happen!

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Comment by Arslanbekov** [comment]
@GrahamCampbell Could you put the tag?

**Comment by Arslanbekov** [comment]
@GrahamCampbell please, add tag :)

**Comment by GrahamCampbell** [comment]
Don't think we need a tag yet. I want the other things fixed first. You can still install this package using dev stability though. `^2.2@dev` for example.

**Comment by SpiLLeR** [comment]
How we can help you to speed up that?

**Comment by GrahamCampbell** [comment]
Once the other three currently open PRs are merged, I will tag. You could help by completing the other PRs by cherry-picking/rebasing them to your own fork, then applying the requested changes. I don't have time to do this myself I'm afraid.

**Pull request merged**
